# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Demo(object):
    def setupUi(self, Demo):
        Demo.setObjectName("Demo")
        Demo.resize(530, 675)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_images/aperture-1142967_960_720.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Demo.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(Demo)
        self.centralWidget.setObjectName("centralWidget")
        self.camera_one_label = QtWidgets.QLabel(self.centralWidget)
        self.camera_one_label.setEnabled(False)
        self.camera_one_label.setGeometry(QtCore.QRect(30, 20, 180, 180))
        self.camera_one_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.camera_one_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_one_label.setText("")
        self.camera_one_label.setPixmap(QtGui.QPixmap("../_images/Camera_One.png"))
        self.camera_one_label.setScaledContents(True)
        self.camera_one_label.setObjectName("camera_one_label")
        self.camera_two_label = QtWidgets.QLabel(self.centralWidget)
        self.camera_two_label.setEnabled(False)
        self.camera_two_label.setGeometry(QtCore.QRect(320, 20, 180, 180))
        self.camera_two_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.camera_two_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_two_label.setText("")
        self.camera_two_label.setPixmap(QtGui.QPixmap("../_images/Camera_Two.png"))
        self.camera_two_label.setScaledContents(True)
        self.camera_two_label.setObjectName("camera_two_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 270, 491, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.IST_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.IST_label.setObjectName("IST_label")
        self.verticalLayout_2.addWidget(self.IST_label)
        self.IST_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IST_edit.setEnabled(False)
        self.IST_edit.setObjectName("IST_edit")
        self.verticalLayout_2.addWidget(self.IST_edit)
        self.ICI_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ICI_label.setObjectName("ICI_label")
        self.verticalLayout_2.addWidget(self.ICI_label)
        self.ICI_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ICI_spinBox.setEnabled(False)
        self.ICI_spinBox.setObjectName("ICI_spinBox")
        self.verticalLayout_2.addWidget(self.ICI_spinBox)
        self.ISD_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ISD_label.setObjectName("ISD_label")
        self.verticalLayout_2.addWidget(self.ISD_label)
        self.ISD_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ISD_spinBox.setEnabled(False)
        self.ISD_spinBox.setObjectName("ISD_spinBox")
        self.verticalLayout_2.addWidget(self.ISD_spinBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 491, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.email = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.email.setObjectName("email")
        self.verticalLayout_3.addWidget(self.email)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.email_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.email_edit.setEnabled(False)
        self.email_edit.setObjectName("email_edit")
        self.horizontalLayout.addWidget(self.email_edit)
        self.confirm_email = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.confirm_email.setEnabled(False)
        self.confirm_email.setCheckable(False)
        self.confirm_email.setObjectName("confirm_email")
        self.horizontalLayout.addWidget(self.confirm_email)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(170, 530, 181, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sync = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sync.setEnabled(False)
        self.sync.setObjectName("sync")
        self.verticalLayout.addWidget(self.sync)
        self.start = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.start.setEnabled(False)
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.cam_one_stat = QtWidgets.QLabel(self.centralWidget)
        self.cam_one_stat.setGeometry(QtCore.QRect(30, 210, 181, 20))
        self.cam_one_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.cam_one_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cam_one_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_one_stat.setObjectName("cam_one_stat")
        self.cam_two_stat = QtWidgets.QLabel(self.centralWidget)
        self.cam_two_stat.setGeometry(QtCore.QRect(320, 210, 181, 20))
        self.cam_two_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.cam_two_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cam_two_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_two_stat.setObjectName("cam_two_stat")
        self.cam_one_power = QtWidgets.QPushButton(self.centralWidget)
        self.cam_one_power.setGeometry(QtCore.QRect(30, 240, 181, 23))
        self.cam_one_power.setObjectName("cam_one_power")
        self.cam_two_power = QtWidgets.QPushButton(self.centralWidget)
        self.cam_two_power.setGeometry(QtCore.QRect(320, 240, 181, 23))
        self.cam_two_power.setObjectName("cam_two_power")
        Demo.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(Demo)
        self.statusBar.setObjectName("statusBar")
        Demo.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(Demo)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 530, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menuBar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuPreset = QtWidgets.QMenu(self.menuBar)
        self.menuPreset.setObjectName("menuPreset")
        Demo.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuFormat.menuAction())
        self.menuBar.addAction(self.menuPreset.menuAction())

        self.retranslateUi(Demo)
        QtCore.QMetaObject.connectSlotsByName(Demo)

    def retranslateUi(self, Demo):
        _translate = QtCore.QCoreApplication.translate
        Demo.setWindowTitle(_translate("Demo", "ABCD DEMO"))
        self.IST_label.setText(_translate("Demo", "Image Sequence Title:"))
        self.ICI_label.setText(_translate("Demo", "Image Capture Interval:"))
        self.ISD_label.setText(_translate("Demo", "Image Sequence Duration:"))
        self.email.setText(_translate("Demo", "Email Address:"))
        self.confirm_email.setText(_translate("Demo", "Confirm"))
        self.sync.setText(_translate("Demo", "Synchronize"))
        self.start.setText(_translate("Demo", "Start"))
        self.cam_one_stat.setText(_translate("Demo", "Status: CONNECTING..."))
        self.cam_two_stat.setText(_translate("Demo", "Status: CONNECTING..."))
        self.cam_one_power.setText(_translate("Demo", "DISABLE"))
        self.cam_two_power.setText(_translate("Demo", "DISABLE"))
        self.menuFile.setTitle(_translate("Demo", "File"))
        self.menuEdit.setTitle(_translate("Demo", "Edit"))
        self.menuFormat.setTitle(_translate("Demo", "Format"))
        self.menuPreset.setTitle(_translate("Demo", "Preset"))

